# Generated by Django 4.0.5 on 2022-06-21 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='제목')),
                ('thumbnail', models.TextField(max_length=256, verbose_name='썸네일')),
                ('desc', models.TextField(max_length=256, verbose_name='설명')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='등록 일자')),
                ('start_view', models.DateTimeField(null=True, verbose_name='노출 시작일')),
                ('end_view', models.DateTimeField(null=True, verbose_name='노출 종료일')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
        ),
    ]
