# Generated by Django 4.0.5 on 2022-06-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.FileField(upload_to='product/', verbose_name='썸네일'),
        ),
    ]
