# Generated by Django 4.0.5 on 2022-06-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='end_view',
            field=models.DateTimeField(verbose_name='노출 종료일'),
        ),
    ]
